name: Prices CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Maven clean install
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Verify code coverage
        run: mvn org.jacoco:jacoco-maven-plugin:check
